spring.config.import=optional:file:.env[.properties]
spring.application.name=Auth-Service
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#JWT CONFIG
jwt.secret=${JWT_SECRET:intellihire-super-secret-key-should-be-long-and-secure}
jwt.access-token-expiry=${ACCESS_TOKEN_EXP:900000}
jwt.refresh-token-expiry=${REFRESH_TOKEN_EXP:604800000}



